services:
  - type: web
    name: genzflow-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: hostinger-mysql
          property: host
      - key: DB_USER
        fromDatabase:
          name: hostinger-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hostinger-mysql
          property: password
      - key: DB_NAME
        fromDatabase:
          name: hostinger-mysql
          property: database
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
