name: Build and Deploy GenZFlow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    # Build Frontend
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
      env:
        NODE_ENV: production
    
    # Prepare Backend
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install --production
    
    # Deploy Frontend
    - name: Deploy Frontend to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_HOST }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        port: 21
        protocol: ftp
        local-dir: ./frontend/dist/
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
      continue-on-error: true # Don't fail the entire workflow if FTP fails
    
    # Deploy Backend
    - name: Deploy Backend to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_HOST }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        port: 21
        protocol: ftp
        local-dir: ./backend/
        server-dir: /backend/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/logs/**
          **/uploads/**
          **/.env*
      continue-on-error: true # Don't fail the entire workflow if FTP fails

    # Alternative: Upload artifacts for manual deployment
    - name: Upload Frontend Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: genzflow-frontend-dist
        path: frontend/dist/
        retention-days: 7

    - name: Upload Backend Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: genzflow-backend-code
        path: backend/
        retention-days: 7
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/logs/**
          **/uploads/**
          **/.env*
    
    # Success Message
    - name: Deployment Success
      run: |
        echo "🎉 GenZFlow build completed!"
        echo ""
        echo "✅ Frontend: Built and ready for deployment"
        echo "✅ Backend: Built and ready for deployment"
        echo "✅ Artifacts: Available for manual upload if FTP fails"
        echo ""
        echo "📁 Download artifacts from the 'Summary' tab if FTP deployment failed"
        echo "🔧 Manual deployment instructions:"
        echo "   1. Download 'genzflow-frontend-dist' artifact"
        echo "   2. Upload contents to /public_html/ in Hostinger File Manager"
        echo "   3. Download 'genzflow-backend-code' artifact"
        echo "   4. Upload contents to /backend/ in Hostinger File Manager"
        echo ""
        echo "🌐 Your site will be available at: https://genzflow.genzspace.in"
