name: Build and Deploy GenZFlow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    # Build Frontend
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
      env:
        NODE_ENV: production
    
    # Prepare Backend
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install --production
    
    # Deploy Frontend
    - name: Deploy Frontend to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_HOST }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        local-dir: ./frontend/dist/
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
    
    # Deploy Backend
    - name: Deploy Backend to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.HOSTINGER_FTP_HOST }}
        username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        local-dir: ./backend/
        server-dir: /backend/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/logs/**
          **/uploads/**
          **/.env*
    
    # Success Message
    - name: Deployment Success
      run: |
        echo "🎉 GenZFlow deployed successfully!"
        echo ""
        echo "Frontend: https://genzflow.genzspace.in"
        echo "Backend API: https://genzflow.genzspace.in:5000"
        echo ""
        echo "Next Steps:"
        echo "1. Import database schema via phpMyAdmin:"
        echo "   - Go to Hostinger control panel"
        echo "   - Open phpMyAdmin"
        echo "   - Import backend/database/schema.sql"
        echo ""
        echo "2. Configure environment variables in Hostinger:"
        echo "   - Set up Node.js environment"
        echo "   - Add your database credentials"
        echo ""
        echo "3. Enable Node.js in Hostinger control panel"
        echo "   - Set startup file to: server.js"
        echo "   - Set Node.js version to: 18.x"
