name: Deploy Frontend to Hostinger

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Hostinger

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      run: |
        cd frontend
        rm -rf node_modules package-lock.json
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/dist/
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          **/Thumbs.db

    - name: Deployment Success
      run: |
        echo "🎉 GenZFlow Frontend deployed successfully!"
        echo ""
        echo "🌐 Website: https://genzflow.genzspace.in"
        echo "📁 Static files deployed to Hostinger"
        echo ""
        echo "✅ Deployment Summary:"
        echo "   - Frontend: Hostinger (Static Files)"
        echo "   - Backend: Local Development"
        echo "   - Database: Hostinger MySQL"
        echo ""
        echo "🔧 Next Steps:"
        echo "   1. Test your website at https://genzflow.genzspace.in"
        echo "   2. Run backend locally for full functionality"
        echo "   3. Check browser console for any errors"
