name: Deploy Frontend to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm run build

    # Deploy to Hostinger via FTP
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/dist/
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**

    # Success Message
    - name: Deployment Success
      run: |
        echo "🎉 GenZFlow Frontend deployed to Hostinger successfully!"
        echo ""
        echo "🌐 Website: https://genzflow.genzspace.in"
        echo "📁 Static files deployed to Hostinger"
        echo ""
        echo "✅ Deployment complete:"
        echo "   - Frontend: Hostinger (Static Files)"
        echo "   - Backend: Local Development"
        echo "   - Database: Hostinger MySQL"

