name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy-to-vps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm run build

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install --production

    # Deploy to VPS via SSH
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Create directories
          mkdir -p /var/www/genzflow/frontend
          mkdir -p /var/www/genzflow/backend
          
          # Stop existing services
          pm2 stop genzflow-backend || true
          
          # Remove old files
          rm -rf /var/www/genzflow/frontend/*
          rm -rf /var/www/genzflow/backend/*

    # Upload Frontend
    - name: Upload Frontend
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "frontend/dist/*"
        target: "/var/www/genzflow/frontend/"
        strip_components: 2

    # Upload Backend
    - name: Upload Backend
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "backend/*"
        target: "/var/www/genzflow/backend/"
        strip_components: 1

    # Start services
    - name: Start Services
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Set permissions
          chown -R www-data:www-data /var/www/genzflow
          
          # Start backend with PM2
          cd /var/www/genzflow/backend
          pm2 start server.js --name genzflow-backend
          pm2 save
          pm2 startup
          
          # Restart Nginx
          sudo systemctl restart nginx
          
          # Check status
          pm2 status
          sudo systemctl status nginx

    # Success Message
    - name: Deployment Success
      run: |
        echo "🎉 GenZFlow deployed to VPS successfully!"
        echo ""
        echo "🌐 Frontend: https://genzflow.genzspace.in"
        echo "🔧 Backend API: https://genzflow.genzspace.in/api"
        echo ""
        echo "✅ Services running:"
        echo "   - Nginx (reverse proxy)"
        echo "   - PM2 (Node.js process manager)"
        echo "   - MySQL database"

